# Loan Approval Prediction

## Data Preprocessing

In this notebook, we prepare the raw dataset for machine learning.

The preprocessing pipeline includes:

- Loading the raw dataset
- Feature selection
- Removing unnecessary columns
- Encoding categorical variables
- Preparing features and target
- Train-test splitting
- Saving the processed dataset

The output of this notebook will be used in the model training notebook.

In [1]:
# Import Libraries
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

In [2]:
# Load DataSet
df = pd.read_csv("../data/raw/loan_approval_dataset.csv")

df.head()

,loan_id,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value,loan_status
0,1,2,Graduate,No,9600000,29900000,12,778,2400000,17600000,22700000,8000000,Approved
1,2,0,Not Graduate,Yes,4100000,12200000,8,417,2700000,2200000,8800000,3300000,Rejected
2,3,3,Graduate,No,9100000,29700000,20,506,7100000,4500000,33300000,12800000,Rejected
3,4,3,Graduate,No,8200000,30700000,8,467,18200000,3300000,23300000,7900000,Rejected
4,5,5,Not Graduate,Yes,9800000,24200000,20,382,12400000,8200000,29400000,5000000,Rejected

In [3]:
# DataSet Shape
print(f"Rows    : {df.shape[0]}")
print(f"Columns : {df.shape[1]}")

Rows    : 4269
Columns : 13

In [4]:
# Column Names
df.columns

Index(['loan_id', ' no_of_dependents', ' education', ' self_employed',
       ' income_annum', ' loan_amount', ' loan_term', ' cibil_score',
       ' residential_assets_value', ' commercial_assets_value',
       ' luxury_assets_value', ' bank_asset_value', ' loan_status'],
      dtype='object')

## Why are we removing extra spaces from column names?

Some datasets contain accidental leading or trailing spaces in their column names.

These spaces can cause errors during feature selection and model deployment.

Using `str.strip()` standardizes all column names and makes the dataset easier to work with.

In [5]:
df.columns = df.columns.str.strip()

df.columns

Index(['loan_id', 'no_of_dependents', 'education', 'self_employed',
       'income_annum', 'loan_amount', 'loan_term', 'cibil_score',
       'residential_assets_value', 'commercial_assets_value',
       'luxury_assets_value', 'bank_asset_value', 'loan_status'],
      dtype='object')

In [7]:
# Checking missing values
df.isnull().sum()

loan_id                     0
no_of_dependents            0
education                   0
self_employed               0
income_annum                0
loan_amount                 0
loan_term                   0
cibil_score                 0
residential_assets_value    0
commercial_assets_value     0
luxury_assets_value         0
bank_asset_value            0
loan_status                 0
dtype: int64

In [8]:
# Check Duplicate values
df.duplicated().sum()

np.int64(0)

## Why are we removing Loan ID?

`loan_id` is a unique identifier assigned to each loan application.

It does not contain any meaningful information for predicting loan approval and may introduce unnecessary noise into the model.

Removing identifier columns is a common preprocessing practice in machine learning.

In [9]:
df.drop("loan_id", axis=1, inplace=True)

df.head()

,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value,loan_status
0,2,Graduate,No,9600000,29900000,12,778,2400000,17600000,22700000,8000000,Approved
1,0,Not Graduate,Yes,4100000,12200000,8,417,2700000,2200000,8800000,3300000,Rejected
2,3,Graduate,No,9100000,29700000,20,506,7100000,4500000,33300000,12800000,Rejected
3,3,Graduate,No,8200000,30700000,8,467,18200000,3300000,23300000,7900000,Rejected
4,5,Not Graduate,Yes,9800000,24200000,20,382,12400000,8200000,29400000,5000000,Rejected

In [11]:
df.shape

(4269, 12)

In [12]:
categorical_columns = df.select_dtypes(include="object").columns

categorical_columns

Index(['education', 'self_employed', 'loan_status'], dtype='object')

## Why do we encode categorical features?

Machine learning algorithms work with numerical data.

Categorical features such as "Graduate" and "Not Graduate" must be converted into numerical values before model training.

Since our categorical features contain only two categories each, Label Encoding is an appropriate and simple choice.

In [13]:
# Label Encode Features
encoder = LabelEncoder()

df["education"] = encoder.fit_transform(df["education"])

df["self_employed"] = encoder.fit_transform(df["self_employed"])

df.head()

,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value,loan_status
0,2,0,0,9600000,29900000,12,778,2400000,17600000,22700000,8000000,Approved
1,0,1,1,4100000,12200000,8,417,2700000,2200000,8800000,3300000,Rejected
2,3,0,0,9100000,29700000,20,506,7100000,4500000,33300000,12800000,Rejected
3,3,0,0,8200000,30700000,8,467,18200000,3300000,23300000,7900000,Rejected
4,5,1,1,9800000,24200000,20,382,12400000,8200000,29400000,5000000,Rejected

## Why do we encode the target variable?

The target column contains text values ("Approved" and "Rejected").

Classification algorithms require numerical labels.

We convert:

- Approved → 0
- Rejected → 1

This allows the model to learn and predict loan approval outcomes.

In [14]:
target_encoder = LabelEncoder()

df["loan_status"] = target_encoder.fit_transform(df["loan_status"])

df.head()

,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value,loan_status
0,2,0,0,9600000,29900000,12,778,2400000,17600000,22700000,8000000,0
1,0,1,1,4100000,12200000,8,417,2700000,2200000,8800000,3300000,1
2,3,0,0,9100000,29700000,20,506,7100000,4500000,33300000,12800000,1
3,3,0,0,8200000,30700000,8,467,18200000,3300000,23300000,7900000,1
4,5,1,1,9800000,24200000,20,382,12400000,8200000,29400000,5000000,1

In [15]:
# Verify Encoding
df.head()

,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value,loan_status
0,2,0,0,9600000,29900000,12,778,2400000,17600000,22700000,8000000,0
1,0,1,1,4100000,12200000,8,417,2700000,2200000,8800000,3300000,1
2,3,0,0,9100000,29700000,20,506,7100000,4500000,33300000,12800000,1
3,3,0,0,8200000,30700000,8,467,18200000,3300000,23300000,7900000,1
4,5,1,1,9800000,24200000,20,382,12400000,8200000,29400000,5000000,1

In [16]:
df.dtypes

no_of_dependents            int64
education                   int64
self_employed               int64
income_annum                int64
loan_amount                 int64
loan_term                   int64
cibil_score                 int64
residential_assets_value    int64
commercial_assets_value     int64
luxury_assets_value         int64
bank_asset_value            int64
loan_status                 int64
dtype: object

In [17]:
# Features and Target
X = df.drop("loan_status", axis=1)

y = df["loan_status"]

print("Features Shape :", X.shape)
print("Target Shape   :", y.shape)

Features Shape : (4269, 11)
Target Shape   : (4269,)

,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value
0,2,0,0,9600000,29900000,12,778,2400000,17600000,22700000,8000000
1,0,1,1,4100000,12200000,8,417,2700000,2200000,8800000,3300000
2,3,0,0,9100000,29700000,20,506,7100000,4500000,33300000,12800000
3,3,0,0,8200000,30700000,8,467,18200000,3300000,23300000,7900000
4,5,1,1,9800000,24200000,20,382,12400000,8200000,29400000,5000000

## Why do we split the dataset?

To evaluate the model fairly, we divide the data into:

- Training Set (80%)
- Testing Set (20%)

The model learns from the training data and is evaluated on unseen testing data.

Using `stratify=y` ensures that both sets maintain the same proportion of approved and rejected loan applications.

In [20]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

In [22]:
# Check Shapes
print("Training Features :", X_train.shape)
print("Testing Features  :", X_test.shape)

print("Training Target   :", y_train.shape)
print("Testing Target    :", y_test.shape)

Training Features : (3415, 11)
Testing Features  : (854, 11)
Training Target   : (3415,)
Testing Target    : (854,)

## Why do we create a processed dataset?

After completing preprocessing, we save the cleaned dataset for future use.

This ensures that the model training notebook always uses the same processed data, making the workflow organized, reproducible, and efficient.

In [23]:
processed_df = pd.concat([X, y], axis=1)

processed_df.head()

,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value,loan_status
0,2,0,0,9600000,29900000,12,778,2400000,17600000,22700000,8000000,0
1,0,1,1,4100000,12200000,8,417,2700000,2200000,8800000,3300000,1
2,3,0,0,9100000,29700000,20,506,7100000,4500000,33300000,12800000,1
3,3,0,0,8200000,30700000,8,467,18200000,3300000,23300000,7900000,1
4,5,1,1,9800000,24200000,20,382,12400000,8200000,29400000,5000000,1

In [24]:
# Save Processed DataSet
processed_df.to_csv(
    "../data/processed/processed_loan.csv",
    index=False
)

print("✅ Processed dataset saved successfully.")

✅ Processed dataset saved successfully.

In [25]:
# Verify Saved Dataset
pd.read_csv("../data/processed/processed_loan.csv").head()

,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value,loan_status
0,2,0,0,9600000,29900000,12,778,2400000,17600000,22700000,8000000,0
1,0,1,1,4100000,12200000,8,417,2700000,2200000,8800000,3300000,1
2,3,0,0,9100000,29700000,20,506,7100000,4500000,33300000,12800000,1
3,3,0,0,8200000,30700000,8,467,18200000,3300000,23300000,7900000,1
4,5,1,1,9800000,24200000,20,382,12400000,8200000,29400000,5000000,1

# Preprocessing Summary

The following preprocessing steps were completed:

- Cleaned column names by removing extra spaces.
- Verified that the dataset contains no missing values.
- Verified that there are no duplicate records.
- Removed the `loan_id` column as it is not useful for prediction.
- Encoded categorical features (`education` and `self_employed`).
- Encoded the target variable (`loan_status`).
- Split the dataset into training and testing sets using stratified sampling.
- Saved the processed dataset for model training.